// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poliklininka.Infrastructure.EF;

#nullable disable

namespace Poliklininka.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260530182823_18")]
    partial class _18
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Poliklininka.Entities.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("allergies", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.AllergyPatient", b =>
                {
                    b.Property<int>("MedCardId")
                        .HasColumnType("integer")
                        .HasColumnName("medcard_id");

                    b.Property<int>("AllergyId")
                        .HasColumnType("integer")
                        .HasColumnName("allergy_id");

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer");

                    b.HasKey("MedCardId", "AllergyId");

                    b.HasIndex("AllergyId");

                    b.HasIndex("PatientId");

                    b.ToTable("allergy_patient", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.Analysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalysisName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("analysis_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("analyses", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.AnalysisHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisId")
                        .HasColumnType("integer")
                        .HasColumnName("analysis_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<int>("VisitHistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("visit_history_id");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("VisitHistoryId");

                    b.ToTable("analysis_histories", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("appointment_date");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("booking_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.BloodGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("office");

                    b.Property<string>("RhFactor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rh_factor");

                    b.HasKey("Id");

                    b.ToTable("blood_groups", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.ChronicDiseases", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("сronic_diseases", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.MedCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("blood_group_id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<bool?>("Disability")
                        .HasColumnType("boolean")
                        .HasColumnName("disability");

                    b.Property<DateOnly>("OpenDate")
                        .HasColumnType("date")
                        .HasColumnName("open_date");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.HasKey("Id");

                    b.HasIndex("BloodGroupId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("med_cards", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.MedService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<decimal>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cost");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.HasKey("Id");

                    b.ToTable("med_services", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.Reception", b =>
                {
                    b.Property<int>("ReceptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReceptionId"));

                    b.Property<DateTime>("DateRes")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("ReceptionId");

                    b.ToTable("receptions", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.RecipeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dosage");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("duration");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("VisitHistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("visit_history_id");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("VisitHistoryId");

                    b.ToTable("recipe_histories", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("office");

                    b.Property<string>("SlotStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slot_status");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("discriminator");

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Poliklininka.Entities.VisitHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    b.Property<int>("MedServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("med_service_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date")
                        .HasColumnName("visit_date");

                    b.Property<string>("VisitResults")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visit_results");

                    b.Property<TimeOnly>("VisitTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("visit_time");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("MedServiceId");

                    b.HasIndex("PatientId");

                    b.ToTable("visit_histories", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.СronicDiseasesPatient", b =>
                {
                    b.Property<int>("MedCardId")
                        .HasColumnType("integer")
                        .HasColumnName("medcard_id");

                    b.Property<int>("ChronicDiseasesId")
                        .HasColumnType("integer")
                        .HasColumnName("chronic_diseases_id");

                    b.HasKey("MedCardId", "ChronicDiseasesId");

                    b.HasIndex("ChronicDiseasesId");

                    b.ToTable("сronic_diseases_patient", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.Doctor", b =>
                {
                    b.HasBaseType("Poliklininka.Entities.User");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("office");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialization");

                    b.ToTable("doctors", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.Patient", b =>
                {
                    b.HasBaseType("Poliklininka.Entities.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Insurance_Policy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("insurance_policy");

                    b.Property<string>("Phone_number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.AllergyPatient", b =>
                {
                    b.HasOne("Poliklininka.Entities.Allergy", "Allergy")
                        .WithMany("AllergyPatient")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.MedCard", "MedCard")
                        .WithMany("AllergyPatient")
                        .HasForeignKey("MedCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.Patient", null)
                        .WithMany("AllergyPatients")
                        .HasForeignKey("PatientId");

                    b.Navigation("Allergy");

                    b.Navigation("MedCard");
                });

            modelBuilder.Entity("Poliklininka.Entities.AnalysisHistory", b =>
                {
                    b.HasOne("Poliklininka.Entities.Analysis", "Analysis")
                        .WithMany("AnalysisHistories")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.VisitHistory", "VisitHistory")
                        .WithMany("AnalysisHistories")
                        .HasForeignKey("VisitHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("VisitHistory");
                });

            modelBuilder.Entity("Poliklininka.Entities.Appointment", b =>
                {
                    b.HasOne("Poliklininka.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.Schedule", "Schedule")
                        .WithMany("Appointments")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Poliklininka.Entities.MedCard", b =>
                {
                    b.HasOne("Poliklininka.Entities.BloodGroup", "BloodGroup")
                        .WithMany("MedCards")
                        .HasForeignKey("BloodGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.Patient", "Patient")
                        .WithOne("MedCard")
                        .HasForeignKey("Poliklininka.Entities.MedCard", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodGroup");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Poliklininka.Entities.RecipeHistory", b =>
                {
                    b.HasOne("Poliklininka.Entities.Recipe", "Recipe")
                        .WithMany("RecipeHistories")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.VisitHistory", "VisitHistory")
                        .WithMany("RecipeHistories")
                        .HasForeignKey("VisitHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("VisitHistory");
                });

            modelBuilder.Entity("Poliklininka.Entities.Schedule", b =>
                {
                    b.HasOne("Poliklininka.Entities.Doctor", "Doctor")
                        .WithMany("Schedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Poliklininka.Entities.VisitHistory", b =>
                {
                    b.HasOne("Poliklininka.Entities.Appointment", "Appointment")
                        .WithOne("VisitHistory")
                        .HasForeignKey("Poliklininka.Entities.VisitHistory", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.MedService", "MedService")
                        .WithMany("VisitHistories")
                        .HasForeignKey("MedServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.Patient", "Patient")
                        .WithMany("VisitHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("MedService");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Poliklininka.Entities.СronicDiseasesPatient", b =>
                {
                    b.HasOne("Poliklininka.Entities.ChronicDiseases", "ChronicDiseases")
                        .WithMany("HronicDiseasesPatient")
                        .HasForeignKey("ChronicDiseasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.MedCard", "MedCard")
                        .WithMany("HronicDiseasesPatient")
                        .HasForeignKey("MedCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChronicDiseases");

                    b.Navigation("MedCard");
                });

            modelBuilder.Entity("Poliklininka.Entities.Doctor", b =>
                {
                    b.HasOne("Poliklininka.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Poliklininka.Entities.Doctor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Poliklininka.Entities.Patient", b =>
                {
                    b.HasOne("Poliklininka.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Poliklininka.Entities.Patient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Poliklininka.Entities.Allergy", b =>
                {
                    b.Navigation("AllergyPatient");
                });

            modelBuilder.Entity("Poliklininka.Entities.Analysis", b =>
                {
                    b.Navigation("AnalysisHistories");
                });

            modelBuilder.Entity("Poliklininka.Entities.Appointment", b =>
                {
                    b.Navigation("VisitHistory");
                });

            modelBuilder.Entity("Poliklininka.Entities.BloodGroup", b =>
                {
                    b.Navigation("MedCards");
                });

            modelBuilder.Entity("Poliklininka.Entities.ChronicDiseases", b =>
                {
                    b.Navigation("HronicDiseasesPatient");
                });

            modelBuilder.Entity("Poliklininka.Entities.MedCard", b =>
                {
                    b.Navigation("AllergyPatient");

                    b.Navigation("HronicDiseasesPatient");
                });

            modelBuilder.Entity("Poliklininka.Entities.MedService", b =>
                {
                    b.Navigation("VisitHistories");
                });

            modelBuilder.Entity("Poliklininka.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeHistories");
                });

            modelBuilder.Entity("Poliklininka.Entities.Schedule", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Poliklininka.Entities.VisitHistory", b =>
                {
                    b.Navigation("AnalysisHistories");

                    b.Navigation("RecipeHistories");
                });

            modelBuilder.Entity("Poliklininka.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Poliklininka.Entities.Patient", b =>
                {
                    b.Navigation("AllergyPatients");

                    b.Navigation("Appointments");

                    b.Navigation("MedCard");

                    b.Navigation("VisitHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
