// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poliklininka.Infrastructure.EF;

#nullable disable

namespace Poliklininka.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260503144628_tables")]
    partial class tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Poliklininka.Entities.Analysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("НазваниеАнализа")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("название_анализа");

                    b.Property<string>("Описание")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("описание");

                    b.HasKey("Id");

                    b.ToTable("analyses", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.AnalysisHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisId")
                        .HasColumnType("integer")
                        .HasColumnName("analysis_id");

                    b.Property<int>("VisitHistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("visit_history_id");

                    b.Property<string>("Результат")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("результат");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("VisitHistoryId");

                    b.ToTable("analysis_histories", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("ДатаПриема")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("дата_приема");

                    b.Property<DateTime>("ДатаСозданияЗаписи")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("дата_создания_записи");

                    b.Property<string>("СтатусЗаписи")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("статус_записи");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.BloodGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Кабинет")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("кабинет");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("название");

                    b.Property<string>("РезусФактор")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("резус_фактор");

                    b.HasKey("Id");

                    b.ToTable("blood_groups", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Кабинет")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("кабинет");

                    b.Property<string>("Специализация")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("специализация");

                    b.Property<string>("ФИО")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("фио");

                    b.HasKey("Id");

                    b.ToTable("doctors", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.MedCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("blood_group_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("Аллергии")
                        .HasColumnType("text")
                        .HasColumnName("аллергии");

                    b.Property<DateOnly>("ДатаОткрытия")
                        .HasColumnType("date")
                        .HasColumnName("дата_открытия");

                    b.Property<DateOnly>("ДатаРождения")
                        .HasColumnType("date")
                        .HasColumnName("дата_рождения");

                    b.Property<bool>("Инвалидность")
                        .HasColumnType("boolean")
                        .HasColumnName("инвалидность");

                    b.Property<string>("НомерКарты")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("номер_карты");

                    b.Property<string>("ХроническиеЗаболевания")
                        .HasColumnType("text")
                        .HasColumnName("хронические_заболевания");

                    b.HasKey("Id");

                    b.HasIndex("BloodGroupId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("med_cards", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.MedService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Категория")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("категория");

                    b.Property<string>("НазваниеУслуги")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("название_услуги");

                    b.Property<decimal>("Стоимость")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("стоимость");

                    b.HasKey("Id");

                    b.ToTable("med_services", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PatientId"));

                    b.Property<string>("ФИО")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("фио");

                    b.HasKey("PatientId");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.Reception", b =>
                {
                    b.Property<int>("ReceptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReceptionId"));

                    b.Property<DateTime>("DateRes")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("ReceptionId");

                    b.ToTable("Receptions", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Описание")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("описание");

                    b.HasKey("Id");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.RecipeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("VisitHistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("visit_history_id");

                    b.Property<string>("Длительность")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("длительность");

                    b.Property<string>("Дозировка")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("дозировка");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("VisitHistoryId");

                    b.ToTable("recipe_histories", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<TimeOnly>("ВремяНачала")
                        .HasColumnType("time without time zone")
                        .HasColumnName("время_начала");

                    b.Property<TimeOnly>("ВремяОкончания")
                        .HasColumnType("time without time zone")
                        .HasColumnName("время_окончания");

                    b.Property<DateOnly>("Дата")
                        .HasColumnType("date")
                        .HasColumnName("дата");

                    b.Property<string>("Кабинет")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("кабинет");

                    b.Property<string>("СтатусСлота")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("статус_слота");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.VisitHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    b.Property<int>("MedServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("med_service_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<TimeOnly>("ВремяПриема")
                        .HasColumnType("time without time zone")
                        .HasColumnName("время_приема");

                    b.Property<DateOnly>("ДатаПриема")
                        .HasColumnType("date")
                        .HasColumnName("дата_приема");

                    b.Property<string>("РезультатыПриема")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("результаты_приема");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("MedServiceId");

                    b.HasIndex("PatientId");

                    b.ToTable("visit_histories", (string)null);
                });

            modelBuilder.Entity("Poliklininka.Entities.AnalysisHistory", b =>
                {
                    b.HasOne("Poliklininka.Entities.Analysis", "Analysis")
                        .WithMany("AnalysisHistories")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.VisitHistory", "VisitHistory")
                        .WithMany("AnalysisHistories")
                        .HasForeignKey("VisitHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("VisitHistory");
                });

            modelBuilder.Entity("Poliklininka.Entities.Appointment", b =>
                {
                    b.HasOne("Poliklininka.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.Schedule", "Schedule")
                        .WithMany("Appointments")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Poliklininka.Entities.MedCard", b =>
                {
                    b.HasOne("Poliklininka.Entities.BloodGroup", "BloodGroup")
                        .WithMany("MedCards")
                        .HasForeignKey("BloodGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.Patient", "Patient")
                        .WithOne("MedCard")
                        .HasForeignKey("Poliklininka.Entities.MedCard", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodGroup");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Poliklininka.Entities.RecipeHistory", b =>
                {
                    b.HasOne("Poliklininka.Entities.Recipe", "Recipe")
                        .WithMany("RecipeHistories")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.VisitHistory", "VisitHistory")
                        .WithMany("RecipeHistories")
                        .HasForeignKey("VisitHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("VisitHistory");
                });

            modelBuilder.Entity("Poliklininka.Entities.Schedule", b =>
                {
                    b.HasOne("Poliklininka.Entities.Doctor", "Doctor")
                        .WithMany("Schedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Poliklininka.Entities.VisitHistory", b =>
                {
                    b.HasOne("Poliklininka.Entities.Appointment", "Appointment")
                        .WithOne("VisitHistory")
                        .HasForeignKey("Poliklininka.Entities.VisitHistory", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.MedService", "MedService")
                        .WithMany("VisitHistories")
                        .HasForeignKey("MedServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliklininka.Entities.Patient", "Patient")
                        .WithMany("VisitHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("MedService");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Poliklininka.Entities.Analysis", b =>
                {
                    b.Navigation("AnalysisHistories");
                });

            modelBuilder.Entity("Poliklininka.Entities.Appointment", b =>
                {
                    b.Navigation("VisitHistory");
                });

            modelBuilder.Entity("Poliklininka.Entities.BloodGroup", b =>
                {
                    b.Navigation("MedCards");
                });

            modelBuilder.Entity("Poliklininka.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Poliklininka.Entities.MedService", b =>
                {
                    b.Navigation("VisitHistories");
                });

            modelBuilder.Entity("Poliklininka.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedCard");

                    b.Navigation("VisitHistories");
                });

            modelBuilder.Entity("Poliklininka.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeHistories");
                });

            modelBuilder.Entity("Poliklininka.Entities.Schedule", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Poliklininka.Entities.VisitHistory", b =>
                {
                    b.Navigation("AnalysisHistories");

                    b.Navigation("RecipeHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
